CREATE DATABASE SistemaComercial
use SistemaComercial
CREATE TABLE ROL(
ID INT IDENTITY(1,1) PRIMARY KEY,
DESCRIPCION VARCHAR(100)
);
CREATE TABLE USUARIO(
ID INT IDENTITY(1,1) PRIMARY KEY,
NOMBREUSUARIO VARCHAR(50) UNIQUE NOT NULL,
CONSTRASENA VARCHAR(50) NOT NULL,
NOMBRES VARCHAR (100) NOT NULL,
APELLIDOS VARCHAR(100) NOT NULL,
FECHAREGISTRO DATETIME DEFAULT GETDATE(),
ID_ROL INT ,
FOREIGN KEY (ID_ROL) REFERENCES ROL(ID)
);

INSERT INTO ROL(DESCRIPCION) VALUES('Administrador');
INSERT INTO ROL(DESCRIPCION) VALUES('Vendedor')
INSERT INTO USUARIO(NOMBREUSUARIO,CONSTRASENA,NOMBRES,APELLIDOS,ID_ROL) values('lborjas','1234Leyddi*','Leyddi Astrid','Borjas Zamora',1)
INSERT INTO USUARIO(NOMBREUSUARIO,CONSTRASENA,NOMBRES,APELLIDOS,ID_ROL) values('Vendedor','123456*','Vendedor','-',2)


CREATE TABLE PRODUCTOS(
ID INT IDENTITY(1,1) PRIMARY KEY,
CODIGO VARCHAR(50) NOT NULL,
DESCRIPCION VARCHAR(50) NOT NULL,
PVP DECIMAL(6,2) NOT NULL DEFAULT 0,
CANTIDAD DECIMAL(6,2) NOT NULL DEFAULT 0,
FECHAREGISTRO DATETIME DEFAULT GETDATE(),
MARCA VARCHAR(50) NULL,
MODELO VARCHAR(50)
);

CREATE TABLE TIPODOCUMENTO(
ID INT IDENTITY(1,1) PRIMARY KEY,
DESCRIPCION VARCHAR(100) NOT NULL,
);

INSERT INTO TIPODOCUMENTO(DESCRIPCION) VALUES ('CEDULA');
INSERT INTO TIPODOCUMENTO(DESCRIPCION) VALUES ('RIF')

CREATE TABLE CLIENTE(
ID INT IDENTITY(1,1) PRIMARY KEY,
NOMBRES VARCHAR(100) NOT NULL,
NUMERODOCUMENTO VARCHAR(50) NOT NULL,
ID_TIPODOCUMENTO INT NOT NULL
FOREIGN KEY (ID_TIPODOCUMENTO) REFERENCES TIPODOCUMENTO(ID)
);

CREATE TABLE SERIES(
ID INT IDENTITY(1,1) PRIMARY KEY,
SERIE VARCHAR(4) NOT NULL,
CORRELATIVO INT DEFAULT 0 ,
ACTIVO BIT DEFAULT 0
);


CREATE TABLE VENTAS(
ID INT IDENTITY(1,1) PRIMARY KEY,
FECHAREGISTRO DATETIME DEFAULT GETDATE(),
ID_USUARIO INT ,
TOTAL DECIMAL(6,2),
ID_CLIENTE INT ,
ID_SERIE INT 
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
FOREIGN KEY (ID_SERIE) REFERENCES SERIES(ID),
);

CREATE TABLE DETALLE_VENTAS(
ID INT IDENTITY(1,1) PRIMARY KEY,
ID_VENTAS INT NOT NULL,
ID_PRODUCTO INT NOT NULL,
PVP DECIMAL(6,2) NOT NULL DEFAULT 0,
PVP_TOTAL DECIMAL(6,2) NOT NULL DEFAULT 0,
CANTIDAD DECIMAL(6,2) NOT NULL DEFAULT 0,
FOREIGN KEY (ID_VENTAS) REFERENCES VENTAS(ID),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID)
);