USE SistemaComercial
GO
CREATE TABLE MONEDA(
ID INT IDENTITY(1,1) PRIMARY KEY,
DESCRIPCION VARCHAR(50),
);
	INSERT INTO MONEDA(DESCRIPCION) VALUES('Bolivares')
	INSERT INTO MONEDA(DESCRIPCION) VALUES('Dolares')
	INSERT INTO MONEDA(DESCRIPCION) VALUES('Pesos')
CREATE TABLE CAJA(
ID INT IDENTITY(1,1) PRIMARY KEY,
FECHA_APERTURA DATETIME DEFAULT GETDATE(),
FECHA_CIERRE DATETIME NULL,
ID_USUARIO_APERTURA INT NOT NULL,
ID_USUARIO_CIERRE INT NULL,
SALDO_INICIAL DECIMAL(6,2) NOT NULL DEFAULT 0
);


CREATE TABLE DETALLE_CAJA(
ID INT IDENTITY(1,1) PRIMARY KEY,
ID_CAJA INT,
ID_MONEDA INT,
MONTO DECIMAL(6,2) NOT NULL DEFAULT 0,
MONTO_BS DECIMAL(6,2) NOT NULL DEFAULT 0,
TIPO_CAMBIO DECIMAL(6,2) NOT NULL DEFAULT 1,
FOREIGN KEY (ID_CAJA) REFERENCES CAJA(ID),
FOREIGN KEY (ID_MONEDA) REFERENCES MONEDA(ID)
);

CREATE TABLE PAGO(
ID INT IDENTITY(1,1) PRIMARY KEY,
FECHAREGISTRO DATETIME DEFAULT GETDATE(),
MONTO DECIMAL(6,2) NOT NULL DEFAULT 0
);

CREATE TABLE DETALLE_PAGO(
ID INT IDENTITY(1,1) PRIMARY KEY,
ID_DETALLE_CAJA INT,
ID_PAGO INT,
FOREIGN KEY (ID_DETALLE_CAJA) REFERENCES DETALLE_CAJA(ID),
FOREIGN KEY (ID_PAGO) REFERENCES PAGO(ID)

);

ALTER TABLE VENTAS ADD ID_PAGO INT 
ALTER TABLE VENTAS ADD COMPROBANTE VARCHAR(12) 
ALTER TABLE VENTAS ADD CONSTRAINT FK_PAGOS_VENTAS FOREIGN KEY (ID_PAGO) REFERENCES PAGO(ID)


INSERT INTO CAJA (ID_USUARIO_APERTURA) VALUES(1)


