ALTER TABLE DETALLE_CAJA ADD TIPO VARCHAR(200) 

CREATE TABLE PROVEEDOR(
ID INT IDENTITY (1,1) PRIMARY KEY,
DESCRIPCION VARCHAR(100) NOT NULL,
DIRECCION VARCHAR(200) NOT NULL,
NUMERODOCUMENTO VARCHAR(100) NOT NULL,
ID_TIPODOCUMENTO INT NOT NULL,
FOREIGN KEY (ID_TIPODOCUMENTO) REFERENCES TIPODOCUMENTO(ID)
);

CREATE TABLE COMPRAS(
ID INT IDENTITY(1,1) PRIMARY KEY,
FECHAREGISTRO DATETIME DEFAULT GETDATE(),
ID_USUARIO INT ,
TOTAL DECIMAL(6,2),
ID_PROVEEDOR INT ,
SERIE VARCHAR(50) NOT NULL 
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID),
);

CREATE TABLE DETALLE_COMPRAS(
ID INT IDENTITY(1,1) PRIMARY KEY,
ID_COMPRAS INT NOT NULL,
ID_PRODUCTO INT NOT NULL,
PVP DECIMAL(6,2) NOT NULL DEFAULT 0,
PVP_TOTAL DECIMAL(6,2) NOT NULL DEFAULT 0,
CANTIDAD DECIMAL(6,2) NOT NULL DEFAULT 0,
FOREIGN KEY (ID_COMPRAS) REFERENCES COMPRAS(ID),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID)
);