USE SistemaComercial
GO

CREATE PROCEDURE uspEditarProducto
@ID INT,
@PI_CODIGO VARCHAR(50),
@PI_DESCRIPCION VARCHAR(50),
@PI_PVP DECIMAL(6,2) = 0,
@PI_CANTIDAD DECIMAL(6,2) = 0,
@PI_MARCA VARCHAR(50) = NULL,
@PI_MODELO VARCHAR(50) = NULL
AS
BEGIN

	UPDATE PRODUCTOS set Codigo = @PI_CODIGO, DESCRIPCION = @PI_DESCRIPCION, PVP = @PI_PVP, CANTIDAD = @PI_CANTIDAD,
	MARCA = @PI_MARCA, MODELO = @PI_MODELO 
	WHERE ID = @ID


END
GO