USE SistemaComercial
GO

CREATE PROCEDURE uspListarUsuario
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	SELECT US.ID, US.ID_ROL, US.NOMBREUSUARIO, US.CONSTRASENA, US.NOMBRES, US.APELLIDOS, US.FECHAREGISTRO, R.DESCRIPCION AS ROL
	FROM USUARIO US WITH(NOLOCK)
	INNER JOIN ROL R WITH(NOLOCK) ON US.ID_ROL = R.ID
	ORDER BY US.FECHAREGISTRO DESC

END
GO
