USE SistemaComercial
GO
-- =============================================
-- Author:		Leyddi Borjas
-- Create date: 09/06/2022
-- Description:	Registrar venta
-- Example:
-- =============================================
CREATE PROCEDURE uspRegistrarVenta
@PI_MONTO DECIMAL(6,2),
@PI_ID_CLIENTE INT,
@PI_ID_USUARIO INT
AS
BEGIN	
	BEGIN TRY  
    BEGIN TRAN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	DECLARE @V_ID_PAGO
	INT
	INSERT INTO PAGO (MONTO) VALUES(@PI_MONTO)
	SET @V_ID_PAGO = SCOPE_IDENTITY();

	DECLARE @V_ID_SERIE INT, @V_CORRELATIVO INT, @V_COMPROBANTE VARCHAR(12), @V_SERIE VARCHAR(4)
	SELECT @V_ID_SERIE = ID, @V_CORRELATIVO = CORRELATIVO+1, @V_SERIE = SERIE FROM SERIES WITH(NOLOCK) WHERE ACTIVO = 1;

	SET @V_COMPROBANTE=@V_SERIE+ RIGHT('00000000' + Ltrim(Rtrim(@V_CORRELATIVO)),8)

	DECLARE @V_ID_VENTA INT
	INSERT INTO VENTAS (ID_CLIENTE,ID_PAGO,ID_SERIE,ID_USUARIO,TOTAL, COMPROBANTE) VALUES(@PI_ID_CLIENTE,@V_ID_PAGO,@V_ID_SERIE,@PI_ID_USUARIO,@PI_MONTO, @V_COMPROBANTE)
	SET @V_ID_VENTA = SCOPE_IDENTITY();

	UPDATE SERIES SET CORRELATIVO = CORRELATIVO + 1 WHERE ID = @V_ID_SERIE

	SELECT @V_ID_VENTA AS ID_VENTA, @V_ID_PAGO AS ID_PAGO
	COMMIT 
END TRY  
BEGIN CATCH  
   ROLLBACK
END CATCH 
END
GO
