USE SistemaComercial
GO
-- =============================================
-- Author:		Leyddi Borjas
-- Create date: 09/06/2022
-- Description:	Registrar Detalle de caja para el vuelto
-- Example: EXEC
-- =============================================
CREATE PROCEDURE uspRegistrarVuelto
@PI_ID_VENTA INT,
@PI_ID_PAGO INT
AS
BEGIN	
	BEGIN TRY  
    BEGIN TRAN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	DECLARE @MONTO_BS DECIMAL(6,2), @TOTAL_VENTA DECIMAL(6,2), @DIFERENCIA DECIMAL(6,2)
	SELECT @MONTO_BS = SUM(DC.MONTO_BS), @TOTAL_VENTA = VEN.TOTAL 
	FROM DETALLE_CAJA DC WITH(NOLOCK) 
	INNER JOIN DETALLE_PAGO DP WITH(NOLOCK) ON DC.ID = DP.ID_DETALLE_CAJA
	INNER JOIN VENTAS VEN WITH(NOLOCK) ON VEN.ID_PAGO = DP.ID_PAGO
	WHERE VEN.ID = @PI_ID_VENTA
	GROUP BY VEN.TOTAL 

	SET @DIFERENCIA = @MONTO_BS - @TOTAL_VENTA

	IF(@DIFERENCIA > 0)
	BEGIN
		DECLARE @V_ID_CAJA INT

		SELECT @V_ID_CAJA = ID FROM CAJA WITH(NOLOCK) WHERE FECHA_CIERRE IS NULL;

		DECLARE @V_ID_DETALLE_CAJA INT
		INSERT INTO DETALLE_CAJA (ID_MONEDA,MONTO, MONTO_BS, TIPO_CAMBIO,ID_CAJA) VALUES (1,0,@DIFERENCIA*-1,1, @V_ID_CAJA)
		SET @V_ID_DETALLE_CAJA = SCOPE_IDENTITY();

		INSERT INTO DETALLE_PAGO (ID_DETALLE_CAJA,ID_PAGO) VALUES (@V_ID_DETALLE_CAJA,@PI_ID_PAGO)
	END
COMMIT 	

	
END TRY  
BEGIN CATCH  
   ROLLBACK
END CATCH 
END
GO
